### PR TITLE
Skeleton

### PR DESCRIPTION
**Pull request by jerremy777**

### CODE REVIEW

**Comment by jerremy777** [comment]
[setup initial front-end components](https://trello.com/c/7PVXK5ik/46-mock-out-initial-front-end-components)

**Review by charliebailey24 — CHANGES_REQUESTED** [review]
I'm getting a typeError on line 63 when I click TEST: TypeError: _this4.getQuestionsById is not a function

**Comment by charliebailey24** [comment]
Ahh! It looks like getQuestionsById isn't bound in the constructor of App.

**Review by charliebailey24 — COMMENTED** [review]
it's the onClick this.getQuestionsById that's throwing the error. I think just delete it since you move that function to QnA

**Review by charliebailey24 — APPROVED** [review]
Tested functionality and site-read for errors.

**Pull request merged**
